version: 1
description: "Test matplotlib-to-base64 API using Gemini Flash 2.5 and 2.0 via ngrok"

providers:
  - id: google:gemini-2.5-flash
    config:
      apiKey: "AIzaSyAto7z8ff4DnyXMZQHYiU9ubu0lsrgwt-o"
      url: "https://fcf395e5b997.ngrok-free.app/api/getData"
      method: POST
      headers:
        Content-Type: application/json
      body:
        prompt: "{{prompt}}"

  - id: google:gemini-2.0-flash
    config:
      apiKey: "AIzaSyAto7z8ff4DnyXMZQHYiU9ubu0lsrgwt-o"
      url: "https://fcf395e5b997.ngrok-free.app/api/getData"
      method: POST
      headers:
        Content-Type: application/json
      body:
        prompt: "{{prompt}}"

tests:
  - vars:
      prompt: "What's the correlation between the Rank and Peak?"
    assert:
      - type: regex
        value: ".*(0.723|0|none).*"

  - vars:
      prompt: "Draw a scatterplot of Rank and Peak along with a dotted red regression line through it"
    assert:
      - type: contains
        value: "python"

  - vars:
      prompt: "Which is the earliest film that grossed over $1.5 bn?"
    assert:
      - type: contains
        value: "Titanic"

  - vars:
      prompt: "How many $2 bn movies were released before 2000?"
    assert:
      - type: regex
        value: ".*(Zero|0|none|Titanic).*"
